/*
 * This file was automatically generated by EvoSuite
 * Fri Feb 23 15:27:44 GMT 2018
 */

package com.merqury.phoebe.util;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.merqury.phoebe.util.JsfUtil;
import java.util.ArrayList;
import java.util.LinkedList;
import javax.faces.component.UIComponent;
import javax.faces.component.UIInput;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.lang.MockException;
import org.evosuite.runtime.mock.java.lang.MockThrowable;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class JsfUtil_ESTest extends JsfUtil_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      // Undeclared exception!
      try { 
        JsfUtil.isDummySelectItem((UIComponent) null, "");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.merqury.phoebe.util.JsfUtil", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      // Undeclared exception!
      try { 
        JsfUtil.getComponentMessages("\"cBtfu", "\"cBtfu");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("javax.faces.component.UIComponent", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      UIInput uIInput0 = new UIInput();
      boolean boolean0 = JsfUtil.isDummySelectItem(uIInput0, ">y");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      MockException mockException0 = new MockException("dxQ");
      MockThrowable mockThrowable0 = new MockThrowable("dxQ", mockException0);
      Throwable throwable0 = JsfUtil.getRootCause(mockThrowable0);
      assertSame(mockException0, throwable0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      MockException mockException0 = new MockException();
      Throwable throwable0 = JsfUtil.getRootCause(mockException0);
      assertSame(throwable0, mockException0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Throwable throwable0 = JsfUtil.getRootCause((Throwable) null);
      assertNull(throwable0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      ArrayList<String> arrayList0 = new ArrayList<String>();
      arrayList0.add("B^vXO5>uYlzvy{.v");
      // Undeclared exception!
      try { 
        JsfUtil.addErrorMessages(arrayList0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.merqury.phoebe.util.JsfUtil", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      LinkedList<String> linkedList0 = new LinkedList<String>();
      JsfUtil.addErrorMessages(linkedList0);
      assertEquals(0, linkedList0.size());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      MockException mockException0 = new MockException("");
      // Undeclared exception!
      try { 
        JsfUtil.addErrorMessage((Exception) mockException0, "");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.merqury.phoebe.util.JsfUtil", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      MockThrowable mockThrowable0 = new MockThrowable();
      MockException mockException0 = new MockException(mockThrowable0);
      // Undeclared exception!
      try { 
        JsfUtil.addErrorMessage((Exception) mockException0, "");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.merqury.phoebe.util.JsfUtil", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      MockException mockException0 = new MockException();
      // Undeclared exception!
      try { 
        JsfUtil.addErrorMessage((Exception) mockException0, "1EX7h*Fo:=Xz}KPF");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.merqury.phoebe.util.JsfUtil", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      // Undeclared exception!
      try { 
        JsfUtil.addSuccessMessage("Ca nt uNate cmponent\"");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.merqury.phoebe.util.JsfUtil", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      // Undeclared exception!
      try { 
        JsfUtil.addExclamationMessage("dxQ");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.merqury.phoebe.util.JsfUtil", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      JsfUtil jsfUtil0 = new JsfUtil();
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      // Undeclared exception!
      try { 
        JsfUtil.isValidationFailed();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.merqury.phoebe.util.JsfUtil", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      // Undeclared exception!
      try { 
        JsfUtil.addErrorMessage((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.merqury.phoebe.util.JsfUtil", e);
      }
  }
}
